--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.689.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11.02.2022 14:24:02
-- Server version: 8.0.26
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE shop_with_magazines;

--
-- Drop table `bucket`
--
DROP TABLE IF EXISTS bucket;

--
-- Drop table `articles`
--
DROP TABLE IF EXISTS articles;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Set default database
--
USE shop_with_magazines;

--
-- Create table `users`
--
CREATE TABLE users (
  id int NOT NULL AUTO_INCREMENT,
  first_name varchar(255) NOT NULL,
  last_name varchar(255) NOT NULL,
  email varchar(50) NOT NULL,
  password varchar(255) NOT NULL,
  role varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `articles`
--
CREATE TABLE articles (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  price decimal(19, 2) NOT NULL,
  description text DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `bucket`
--
CREATE TABLE bucket (
  id int NOT NULL AUTO_INCREMENT,
  user_id int NOT NULL,
  article_id int NOT NULL,
  purchase_date timestamp NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE bucket
ADD CONSTRAINT article_id_FK FOREIGN KEY (article_id)
REFERENCES articles (id);

--
-- Create foreign key
--
ALTER TABLE bucket
ADD CONSTRAINT user_id_FK FOREIGN KEY (user_id)
REFERENCES users (id) ON DELETE CASCADE;

-- 
-- Dumping data for table users
--
-- Table shop_with_magazines.users does not contain any data (it is empty)

-- 
-- Dumping data for table articles
--
-- Table shop_with_magazines.articles does not contain any data (it is empty)

-- 
-- Dumping data for table bucket
--
-- Table shop_with_magazines.bucket does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;